### ISSUE TITLE
Unsplash bug

### ISSUE THREAD

**Issue by p0k33m0n** [the-wright-jamie/tab-nine#161]
If Unsplash is set as wallpaper it download every time new wallpaper on new tab completely ignoring the settings.

**Comment by the-wright-jamie** [comment]
Will look into ASAP - may not be before the new year, see #160

Just an FYI :)

**Comment by the-wright-jamie** [comment]
Seems like your request has been fixed in #172. I'll get a release out for you soon, should be on your PC before the week is up
