### ISSUE TITLE
NBA scores widget not working

### ISSUE THREAD

**Issue by LukasDahl** [the-wright-jamie/tab-nine#85]
The NBA scores widget is broken on the server side as mentioned here: [tabliss issue #570](https://github.com/joelshepherd/tabliss/issues/570)
It might be best to remove the widget from the list as it only causes confusion.

**Comment by the-wright-jamie** [comment]
Thank you for your bug submission! That sounds like the best course of action, I will fix this soon*

*as per #69, I am rather busy IRL so I don't have a lot of time, but it will be fixed in the next release

**Comment by the-wright-jamie** [comment]
![image](https://github.com/the-wright-jamie/tab-nine/assets/121819290/94f4f851-dadf-438c-85f3-89b6a6c37be1)
Removed. Thanks to #50, people who still have this in their config will not be left with a broken install - it will instead show an unknown widget.
