### ISSUE TITLE
Firefox store version still at 1.1.0

### ISSUE THREAD

**Issue by sbstn87** [the-wright-jamie/tab-nine#90]
Hi,

is there an issue with pushing the latest version to Mozilla's store? It is still at 1.1.0 at the time of writing.

**Comment by the-wright-jamie** [comment]
Yeah that's my bad, I reset my deployment device (my workflow is very scattered atm) and forgot to upload the new package. #22 is supposed to automate this process but I haven't got round to it yet. 

I've some time this morning, I'll fire it out now

**Comment by the-wright-jamie** [comment]
v1.1.1 releasing now

Chrome:
![image](https://github.com/the-wright-jamie/tab-nine/assets/121819290/cfc9df9d-ddb1-446d-a710-20f50620205a)

Firefox:
![image](https://github.com/the-wright-jamie/tab-nine/assets/121819290/bd10293a-ec5f-4320-afeb-d483d636e6c4)
