### ISSUE TITLE
[Feature request] Select multiple Unsplash topics and cycle through a random photo from any of them

### ISSUE THREAD

**Issue by sageDieu** [the-wright-jamie/tab-nine#97]
For the background images, I've found there to be some great images for my tastes across multiple Unsplash topics. Instead of having to swap around manually for these, it would be great if I could, for example, select both "Architecture" and "Nature", and then when a new image is pulled, it randomly picks which topic to choose from.

**Comment by the-wright-jamie** [comment]
Ooo, that's a good one. I'll see about this, definitely worthwhile this one. Thanks for the idea!

**Comment by sageDieu** [comment]
Awesome! Thank you!

**Comment by the-wright-jamie** [comment]
#137 merged, hopefully this meets your request!

**Comment by sageDieu** [comment]
Yeah this is great, thank you very much!!
